name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t todolistapp .
    - name: Tag the Docker image
      run: docker tag todolistapp ar0208/todolist
    - name: Docker login
      run: docker login - u ${{ secrets.DOCKER_USERNAME }} -p ${{ DOCKER_PASSWORD }}
    - name: Docker push
      run: docker push ar0208/todolist
